scenario_creation_task:
  description: >
    Create a comprehensive and realistic business scenario for sustainability messaging training based on the user's
    profile, industry focus, and regional regulatory context. Search extensively for current sustainability trends and 
    real company examples in {user_industry} to make the scenario authentic and timely. 
    
    YOU MUST OUTPUT YOUR RESPONSE AS VALID JSON with this exact structure:
    {{
      "company_name": "specific company name",
      "industry": "{user_industry}",
      "company_size": "specific size (e.g., 'Medium (200-300 employees)')",
      "location": "specific city and country",
      "product_service": "detailed description of products/services with sustainability implications",
      "target_audience": "detailed demographics and psychographics", 
      "marketing_objectives": ["objective 1", "objective 2", "objective 3", "objective 4", "objective 5"],
      "sustainability_context": "current sustainability challenges and context",
      "preliminary_claims": ["claim 1", "claim 2", "claim 3", "claim 4"],
      "regulatory_context": "detailed regulatory context for {regulatory_region}",
      "competitive_landscape": "analysis of competitors and positioning",
      "current_practices": ["practice 1", "practice 2", "practice 3"],
      "challenges_faced": ["challenge 1", "challenge 2", "challenge 3"],
      "market_research_sources": ["source 1", "source 2", "source 3"]
    }}
    
    CRITICAL: Output ONLY the JSON object, no additional text. Ensure all fields are populated with specific,
    realistic content based on your research. Marketing objectives must have at least 5 items.
  expected_output: >
    A single JSON object containing complete business scenario data with all required fields populated.
    Must include specific company details, at least 5 marketing objectives, 4 preliminary claims,
    and comprehensive regulatory context for {regulatory_region}. No additional text outside the JSON.
  agent: scenario_builder

mistake_generation_task:
  description: >
    Based on the business scenario created in the previous task, research real examples of problematic 
    sustainability messages and greenwashing cases in {regulatory_region}. Create exactly 4 detailed 
    problematic sustainability messages that are contextually relevant to the scenario company.
    
    YOU MUST OUTPUT YOUR RESPONSE AS VALID JSON with this exact structure:
    {{
      "scenario_reference": "brief reference to the company from previous task",
      "problematic_messages": [
        {{
          "id": "msg1",
          "message": "the problematic sustainability message text",
          "problems_identified": ["problem 1", "problem 2", "problem 3"],
          "regulatory_violations": ["violation 1", "violation 2"],
          "greenwashing_patterns": ["pattern 1", "pattern 2"],
          "real_world_examples": ["example 1", "example 2"],
          "why_problematic": "detailed explanation of why this message is problematic",
          "potential_consequences": ["consequence 1", "consequence 2"],
          "context_specific_issues": "issues specific to the scenario company",
          "alternative_approaches": ["approach 1", "approach 2"]
        }},
        ... (repeat for msg2, msg3, msg4)
      ],
      "general_patterns_found": ["pattern 1", "pattern 2", "pattern 3"],
      "regulatory_landscape": "overview of {regulatory_region} regulations",
      "research_sources": ["source 1", "source 2", "source 3"],
      "industry_specific_insights": "insights specific to {user_industry}",
      "enforcement_trends": ["trend 1", "trend 2", "trend 3"]
    }}
    
    CRITICAL: Output ONLY the JSON object, no additional text. Must include exactly 4 problematic messages
    (msg1, msg2, msg3, msg4) with all required fields populated for each message.
  expected_output: >
    A single JSON object containing exactly 4 problematic sustainability messages with complete analysis
    for each message including regulatory violations, real-world examples, and context-specific issues.
    No additional text outside the JSON.
  agent: mistake_illustrator
  context:
    - scenario_creation_task

best_practice_transformation_task:
  description: >
    Transform each of the 4 problematic messages from the previous task into compliant, effective alternatives
    by researching current best practices and successful sustainability communications in {regulatory_region}.
    
    YOU MUST OUTPUT YOUR RESPONSE AS VALID JSON with this exact structure:
    {{
      "scenario_reference": "brief reference to the company from scenario task",
      "corrected_messages": [
        {{
          "original_message_id": "msg1",
          "corrected_message": "the improved, compliant message text",
          "changes_made": ["change 1", "change 2", "change 3"],
          "compliance_notes": "how this message ensures regulatory compliance",
          "best_practices_applied": ["practice 1", "practice 2"],
          "real_world_examples": ["company example 1", "company example 2"],
          "effectiveness_rationale": "why this corrected message is effective",
          "evidence_required": ["evidence 1", "evidence 2"],
          "monitoring_suggestions": ["monitoring 1", "monitoring 2"]
        }},
        ... (repeat for msg2, msg3, msg4)
      ],
      "general_guidelines": ["guideline 1", "guideline 2", "guideline 3"],
      "key_principles": ["principle 1", "principle 2", "principle 3"],
      "regulatory_compliance_tips": ["tip 1", "tip 2", "tip 3"],
      "industry_specific_advice": "advice specific to {user_industry}",
      "research_sources": ["source 1", "source 2", "source 3"]
    }}
    
    CRITICAL: Output ONLY the JSON object, no additional text. Must include exactly 4 corrected messages
    corresponding to msg1, msg2, msg3, msg4 with all required fields populated.
  expected_output: >
    A single JSON object containing exactly 4 corrected messages with detailed improvements, compliance
    notes, and evidence requirements for each correction. No additional text outside the JSON.
  agent: best_practice_coach
  context:
    - scenario_creation_task
    - mistake_generation_task

implementation_task:
  description: >
    Create a comprehensive implementation roadmap and success metrics framework based on all previous tasks.
    Develop practical guidance that the scenario company can use to implement sustainable messaging practices.
    
    YOU MUST OUTPUT YOUR RESPONSE AS VALID JSON with this exact structure:
    {{
      "scenario_reference": "brief reference to the company from scenario task",
      "implementation_roadmap": [
        "step 1: detailed implementation step",
        "step 2: detailed implementation step", 
        "step 3: detailed implementation step",
        "step 4: detailed implementation step",
        "step 5: detailed implementation step",
        "step 6: detailed implementation step"
      ],
      "success_metrics": [
        "metric 1: specific measurable outcome",
        "metric 2: specific measurable outcome",
        "metric 3: specific measurable outcome", 
        "metric 4: specific measurable outcome",
        "metric 5: specific measurable outcome"
      ],
      "timeline_milestones": [
        "month 1: milestone description",
        "month 3: milestone description",
        "month 6: milestone description",
        "month 12: milestone description"
      ],
      "team_training_requirements": [
        "training requirement 1",
        "training requirement 2", 
        "training requirement 3"
      ],
      "tools_and_resources": [
        "tool/resource 1",
        "tool/resource 2",
        "tool/resource 3"
      ],
      "risk_mitigation": [
        "risk 1 and mitigation strategy",
        "risk 2 and mitigation strategy",
        "risk 3 and mitigation strategy"
      ],
      "industry_specific_considerations": "considerations specific to {user_industry}",
      "regulatory_compliance_schedule": "schedule for ongoing compliance activities",
      "budget_considerations": "estimated budget and resource requirements"
    }}
    
    CRITICAL: Output ONLY the JSON object, no additional text. Must include at least 6 implementation
    steps and 5 success metrics with specific, actionable content.
  expected_output: >
    A single JSON object containing comprehensive implementation guidance with at least 6 roadmap steps,
    5 success metrics, timeline milestones, and practical considerations. No additional text outside the JSON.
  agent: playbook_creator
  context:
    - scenario_creation_task
    - mistake_generation_task
    - best_practice_transformation_task